version: '3.8'

services:
  linkedpurry-db:
    image: postgres:14-alpine
    container_name: linkedpurry-db
    hostname: linkedpurry-db
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      linkedpurry-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
